import type { CollectionConfig } from 'payload'
import { isAdmin } from '@/access/isAdmin'

export const PrintifyCatalogCache: CollectionConfig = {
  slug: 'printify-catalog-cache',
  labels: { singular: 'Catalog Cache', plural: 'Catalog Cache' },
  admin: {
    group: 'Automate',
    hidden: true,
  },
  access: {
    create: isAdmin,
    read: isAdmin,
    update: isAdmin,
    delete: isAdmin,
  },
  fields: [
    { name: 'blueprintId', type: 'number', required: true, index: true },
    { name: 'providerId', type: 'number', required: true, index: true },
    { name: 'blueprintTitle', type: 'text' },
    { name: 'blueprintBrand', type: 'text' },
    { name: 'blueprintModel', type: 'text' },
    { name: 'blueprintImages', type: 'json' },
    { name: 'providerTitle', type: 'text' },
    { name: 'decorationMethods', type: 'json' },
    { name: 'category', type: 'text', index: true },
    { name: 'minCost', type: 'number' },
    { name: 'maxCost', type: 'number' },
    { name: 'shippingCostUs', type: 'number' },
    { name: 'handlingTime', type: 'text' },
    { name: 'targetRetail', type: 'number' },
    { name: 'marginPercent', type: 'number' },
    { name: 'profitPerUnit', type: 'number' },
    { name: 'totalVariants', type: 'number' },
    { name: 'enabledVariants', type: 'number' },
    { name: 'availableColors', type: 'json' },
    { name: 'brandColorsAvailable', type: 'json' },
    { name: 'brandColorCount', type: 'number' },
    { name: 'availableSizes', type: 'json' },
    { name: 'sizeRange', type: 'text' },
    { name: 'printAreaFront', type: 'json' },
    { name: 'printAreaBack', type: 'json' },
    { name: 'printAreaCount', type: 'number' },
    { name: 'score', type: 'number', index: true },
    { name: 'scoreBreakdown', type: 'json' },
    { name: 'lastSyncedAt', type: 'date' },
    { name: 'firstSeenAt', type: 'date' },
    { name: 'syncVersion', type: 'number' },
    { name: 'status', type: 'select', options: ['active', 'discontinued', 'error'], defaultValue: 'active' },
    { name: 'lastSyncError', type: 'text' },
    { name: 'dataHash', type: 'text' },
    // Full variant array: [{ variantId, title, color, size, cost, isEnabled, isAvailable, options }]
    { name: 'variants', type: 'json', admin: { description: 'Full variant array with IDs, parsed colors/sizes, per-variant cost' } },
  ],
}
